apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example
  labels:
    app: example
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/data"