apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-example
  labels:
    app: example
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi